@echo off  
curl.exe -X GET http://localhost:9005/api/instructor/courses -H \"Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsInJvbGUiOiJpbnN0cnVjdG9yIiwiZW1haWwiOiJpbnN0cnVjdG9yMUBleGFtcGxlLmNvbSIsIm9yZ2FuaXphdGlvbklkIjoyLCJpYXQiOjE3NDM2OTk0MzksImV4cCI6MTc0Mzc4NTgzOX0.wqjvJAjG84h_3oviKxhJb1o_1_J5gs_7-Yi-6_g_S4k\" 
